overlays/urls.py
from django.urls import path

from . import views

app_name = 'overlays'
urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
    path('<int:overlay_id>', views.show, name='show'),
    path('<int:overlay_id>.json', views.show, name='json_show'),
]

plumify/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('overlays.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

overlays/models.py
import requests
import uuid
import tempfile

from django.core import files
from django.db import models
from PIL import Image

from .maps.google_maps import GoogleMaps

def plume_path(instance, filename):
    return 'plumes/{}_{}.png'.format(instance.name, uuid.uuid4())

def satallite_map_path(instance, filename):
    return 'sat_maps/{}_{}.png'.format(instance.name, uuid.uuid4())

def processed_map_path(instance, filename):
    return 'processed/{}_{}.png'.format(instance.name, uuid.uuid4())

class Overlay(models.Model):
    GHG_OFFICE_LATITIUDE = 45.516750
    GHG_OFFICE_LONGTITUDE = -73.578500

    name = models.CharField(max_length=200)
    latitude = models.FloatField()
    longtitude = models.FloatField()
    plume = models.ImageField(upload_to=plume_path)
    satallite_map = models.ImageField(upload_to=satallite_map_path, blank=True, null=True)
    plume_on_satallite_map = models.ImageField(upload_to=processed_map_path, blank=True, null=True)

    def __str__(self):
        return "{} ({})".format(self.id, self.name)

    def download_satellite_map_and_save(self):
        response = requests.get(self.satellite_map_url(), allow_redirects=True, stream=True)
        if response.status_code != requests.codes.ok:
            raise Exception("Unable to download satallite image")
        temp_file = tempfile.NamedTemporaryFile()
        for block in response.iter_content(1024 * 8):
            if not block:
                break
            temp_file.write(block)
        self.satallite_map.save("ignored.png", files.File(temp_file))

    def generate_plume_on_satallite_map(self):
        background = Image.open(self.satallite_map).convert('RGBA')
        foreground = Image.open(self.plume).convert('RGBA')
        combined = Image.new('RGBA', background.size)
        combined.paste(background, (0,0), background)
        combined.paste(foreground, (0,0), foreground)
        temp_file = tempfile.NamedTemporaryFile()
        combined.save(fp=temp_file, format='PNG')
        self.plume_on_satallite_map.save("ignored.png", files.File(temp_file))

    def process_and_save(self):
        self.download_satellite_map_and_save()
        self.generate_plume_on_satallite_map()

    def satellite_map_url(self):
        return GoogleMaps().url(self.latitude, self.longtitude)

    def as_dict(self):
        """
        Convert the overlay to it's cannonical representation as a dict, suitable for use dumping to JSON
        """
        return {
            'name': self.name,
            'latitude': self.latitude,
            'longtitude': self.longtitude,
            'plume': self.plume.url,
            'plume_on_satallite_map': self.plume_on_satallite_map.url,
            'satallite_map': self.satallite_map.url,
        }

overlays/forms.py
from django.forms import ModelForm

from overlays.models import Overlay

class OverlayForm(ModelForm):
    class Meta:
        model = Overlay
        fields = ['name', 'latitude', 'longtitude', 'plume']

overlays/views.py
from django.core import serializers
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse

from django.forms.models import model_to_dict

from .models import Overlay
from .forms import OverlayForm

def index(request):
    overlays = Overlay.objects.all()
    context = {'overlays': overlays}
    return render(request, 'overlays/index.html', context)

def new(request):
    if request.method == 'POST':
        overlay_form = OverlayForm(request.POST, request.FILES)
        if overlay_form.is_valid():
            overlay = overlay_form.save(commit=False)
            overlay.process_and_save()
            return HttpResponseRedirect(reverse('overlays:show', args=(overlay.id,)))
    else:
        overlay_form = OverlayForm()
    return render(request, 'overlays/new.html', {'overlay_form': overlay_form})

def show(request, overlay_id):
    overlay = get_object_or_404(Overlay, pk=overlay_id)
    if request.path.endswith(".json"):
        return JsonResponse(overlay.as_dict())
    else:
        return render(request, 'overlays/show.html', {'overlay': overlay})

overlays/templates/overlays/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'overlays/styles.css' %}">
    </head>

    <body>
        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

overlays/templates/overlays/index.html
{% extends 'overlays/base.html' %}

{% block content %}
    <h1>Overlays</h1>

    <div>
    <a class="btn btn-primary" href="{%url 'overlays:new' %}" role="button">New overlay</a>
    </div>

    <div>
        <h2>Existing Overlays:</h2>
        <ul>
            {% for overlay in overlays %}
            <li><a href="{% url 'overlays:show' overlay.id %}">{{ overlay.name }}</a></li>
            {% empty %}
            <li>No overlays yet</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

overlays/templates/overlays/new.html
{% extends 'overlays/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h1>Create new overlay</h1>

<form enctype="multipart/form-data" action="{% url 'overlays:new' %}" method="post">
      <div class="form-group">
        {% csrf_token %}
        {{ overlay_form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </div>
</form>
{% endblock %}

overlays/templates/overlays/show.html
{% extends 'overlays/base.html' %}

{% block content %}
<h1>{{ overlay.name }}</h1>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Co-ordinates</h4>
        <p>Lattitude: {{overlay.latitude}}</p>
        <p>Longtitude: {{overlay.longtitude}}</p>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Plume on Satallite Map</h4>
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#plume_on_satallite_map" aria-expanded="true" aria-controls="collapseOne">
            Show/Hide
        </button>
    </div>
    <img id="plume_on_satallite_map" class="map collapse show" src="{{overlay.plume_on_satallite_map.url}}" />
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Raw Satallite Map</h4>
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#satallite_map" aria-expanded="true" aria-controls="collapseOne">
            Show/Hide
        </button>
    </div>
    <img id="satallite_map" class="map collapse" src="{{overlay.satallite_map.url}}" />
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Raw Plume</h4>
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#plume" aria-expanded="true" aria-controls="collapseOne">
            Show/Hide
        </button>
    </div>
    <img id="plume" class="map collapse" src="{{overlay.plume.url}}" />
</div>
{% endblock %}